idf_component_register(
    SRCS
        "app_main.cpp"
        "control_task.cpp"
        "profiles/profile_normal.cpp"
        "profiles/profile_twai_loopback.cpp"
        "profiles/profile_imu_only.cpp"
        "profiles/profile_motor_test.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        config
        can_bus
        rs02_motor
        witmotion_imu
        esp_timer
        nvs_flash
        driver
        log
)
